### ISSUE TITLE
Snakes still go through walls

### ISSUE THREAD

**Issue by ValerieRoussel** [ZuhabWasim/TOJam2022#55]
The snakes turn around when they hit the edge of the floor but they are still going through walls freely.

See the snakes in DesertLevel scene

**Comment by fridgetheorem** [comment]
@jtan537 is this related to the walking stick mechanic for the snakes? (do you still push them backwards on collision?)

**Comment by ValerieRoussel** [comment]
fixed, snake collider was inside ground so they were in constant collision
