### ISSUE TITLE
Change aggro trigger to be a separate component

### ISSUE THREAD

**Issue by fridgetheorem** [ZuhabWasim/TOJam2022#61]
# All enemies should have a dedicated aggro zone/Enemy overhaul?
The old model where the player told the enemy when they were aggroed worked in this way, but with the new system the enemy itself has 2 colliders on it, 1 for aggro 1 for hitbox.

Unfortunately, the player can hit the aggro trigger with their sword (#58). Now, we need to create a script that manages aggro, and pass the results to the enemy's controller.

Ideally this would be part of the enemy script overhaul but that will be additional architecture work.

**Comment by ZuhabWasim** [comment]
Let's assign this to Jimmy
